services:
  web:
    build:
      context: .
      dockerfile: apps/spring-notes-ui/Dockerfile
    ports:
      - "8080:80"
  connect:
    build:
      context: .
      dockerfile: apps/sprint-notes-connect/Dockerfile
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: production
      PORT: 3333
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-LollyGobbleBlissBombs}@db:5432/${POSTGRES_DB:-notes}
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-LollyGobbleBlissBombs}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-notes}
    volumes:
      - db:/data/postgres

volumes:
  db:
    